#
# Copyright (c) 2019 Broadcom.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Broadcom, Inc. - initial API and implementation
#

name: Alpine build
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
jobs:
  alpine-build:
      name: Linux language server
      runs-on: ubuntu-18.04
      container:
        image: alpine:3.10
      
      steps:
      - uses: actions/checkout@v1
      - name: Requirements install
        run: apk update && apk add --no-cache linux-headers git g++ cmake util-linux-dev npm ninja pkgconfig openjdk8 maven
      - name: Configure
        run: mkdir build && cd build && cmake -G Ninja ../
      - name: Build
        run: cd build && cmake --build .
      - name: Server Test
        run: cd build/bin && ./server_test && ./library_test
      - name: Extension Test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm --prefix clients/vscode-hlasmplugin test
      - name: Get VSIX filename
        run: echo ::set-env name=VSIX_FILENAME::$(ls build/bin/*.vsix)
      - name: Get version
        run: echo ::set-env name=VERSION::$(node -e "console.log(require('./clients/vscode-hlasmplugin/package.json').version)") 
      - name: Rename VSIX
        run: mv ${{ env.VSIX_FILENAME }} hlasm-language-support-alpine-${{ env.VERSION }}.vsix
      - name: Upload VSIX
        uses: actions/upload-artifact@v1
        with:
          name: hlasm-language-support-alpine-${{ env.VERSION }}.vsix
          path: hlasm-language-support-alpine-${{ env.VERSION }}.vsix
