#
# Copyright (c) 2019 Broadcom.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Broadcom, Inc. - initial API and implementation
#

name: Check

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  clang-asan:
    name: Clang ASAN, UBSAN
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Requirements install
        run: sudo apt-get update && sudo apt-get install uuid-dev ninja-build libc++-12-dev libc++abi-12-dev
      - name: Configure
        run: mkdir build && cd build && cmake -G Ninja -DBUILD_VSIX=Off -DCMAKE_C_COMPILER=clang-12 -DCMAKE_CXX_COMPILER=clang++-12 -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined" ../
      - name: Build
        run: cd build && cmake --build .
      - name: Test
        run: cd build/bin && ./server_test && ./library_test
  
  clang-tsan:
    name: Clang TSAN
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Requirements install
        run: sudo apt-get update && sudo apt-get install uuid-dev ninja-build libc++-12-dev libc++abi-12-dev
      - name: Configure
        run: mkdir build && cd build && cmake -G Ninja -DBUILD_VSIX=Off -DCMAKE_C_COMPILER=clang-12 -DCMAKE_CXX_COMPILER=clang++-12 -DCMAKE_CXX_FLAGS="-fsanitize=thread" ../
      - name: Build
        run: cd build && cmake --build .
      - name: Test
        run: cd build/bin && ./server_test && ./library_test

  clang-format-check:
    name: Code format
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Requirements install
        run: sudo apt-get install -y clang-format-12
      - name: Run clang-format
        run: clang-format-12 -style=file -n $(find . -name \*.h -print -o -name \*.cpp -print) 2>&1 | tee clang-format-output.txt
      - name: Upload clang-format-output.txt
        uses: actions/upload-artifact@v1
        with:
          name: clang-format-output
          path: clang-format-output.txt
      - name: Check format
        run: |
          if [ -s clang-format-output.txt ]
          then
            exit 1
          fi

  license-headers:
    name: License headers check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Check license headers
        run: |
          chmod +x cmake/check_license.sh
          cmake/check_license.sh

  pr-base-check:
    name: Master PR check
    runs-on: ubuntu-20.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Check, whether PR to master is from a release branch
        if: github.base_ref == 'master' && !contains(github.head_ref, 'release')
        run: exit 1
