#
# Copyright (c) 2019 Broadcom.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Broadcom, Inc. - initial API and implementation
#

name: Check
on:
  push:
    branches:
      - master
      - development
      - release-*
  pull_request:
    branches:
      - master
      - development

jobs:
  
  clang:
      name: Clang ASAN, UBSAN
      runs-on: ubuntu-18.04
      
      steps:
      - uses: actions/checkout@v1
      - name: Requirements install
        run: sudo apt-get update && sudo apt-get install uuid-dev ninja-build libc++-8-dev libc++abi-8-dev
      - name: Configure
        run: mkdir build && cd build && cmake -G Ninja -DBUILD_VSIX=Off -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined,fuzzer-no-link" ../
      - name: Build
        run: cd build && cmake --build .
      - name: Test
        run: cd build/bin && ./server_test && ./library_test
  
  clang-format-check:
      name: Code format
      runs-on: ubuntu-18.04
      
      steps:
      - uses: actions/checkout@v1
      - name: Requirements install
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
          sudo apt-get update
          sudo apt-get install -y clang-format-10
      #Change the options in clang format that make clang-format-10 output different source than clang-format-9
      - name: Clang format 10 compatiblity
        run: |
          echo "SpaceInEmptyBlock: false" >> .clang-format
      - name: Format check
        run:  clang-format-10 -style=file -n $(find . -name \*.h -print -o -name \*.cpp -print) 2>&1 | tee clang-format-output.txt
      - name: Upload clang-format-output.txt
        uses: actions/upload-artifact@v1
        with:
          name: clang-format-output
          path: clang-format-output.txt
  
  license-headers:
      name: License headers
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@v1
      - name: Check license headers
        run: |
          chmod +x cmake/check_license.sh
          cmake/check_license.sh

  pr-base-check:
      name: Base branch
      runs-on: ubuntu-18.04
      if: github.event_name == 'pull_request'
      steps:
      - name: Fail, if PR base is master
        if: contains(github.base_ref, 'master') && !contains(github.head_ref, 'release')
        run: exit 1
        
